Repository googleapis/python-pubsublite, pull requests merged in 2020-11, with the labels that each got.

#63 chore: update synth.py to exclude a file
  synth.py
Labels: cla: yes

#61 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .github/snippet-bot.yml
  .gitignore
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/populate-secrets.sh
  .kokoro/publish-docs.sh
  .kokoro/release/common.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/test-samples.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  CODE_OF_CONDUCT.md
  CONTRIBUTING.rst
  docs/conf.py
  google/cloud/pubsublite_v1/__init__.py
  noxfile.py
  samples/snippets/noxfile.py
  samples/snippets/requirements.txt
  scripts/decrypt-secrets.sh
  synth.metadata
Labels: cla: yes, context: partial

#59 chore: add kokoro to required status check
  .github/sync-repo-settings.yaml
Labels: cla: yes

#68 chore: update synth.py and noxfile
  .gitignore
  .kokoro/docker/docs/Dockerfile
  .repo-metadata.json
  noxfile.py
  synth.metadata
  synth.py
Labels: api: pubsublite, cla: yes

#70 fix: Enforce that __enter__ is called on all user interfaces before use
  google/cloud/pubsublite/cloudpubsub/publisher_client.py
  google/cloud/pubsublite/cloudpubsub/subscriber_client.py
  google/cloud/pubsublite/internal/require_started.py
  samples/snippets/subscriber_example.py
Labels: api: pubsublite, cla: yes

#66 docs: add documentation
  docs/admin/api/client.rst
  docs/admin/index.rst
  docs/conf.py
  docs/index.rst
  docs/publisher/api/client.rst
  docs/publisher/index.rst
  docs/pubsublite_v1/services.rst
  docs/pubsublite_v1/types.rst
  docs/subscriber/api/client.rst
  docs/subscriber/index.rst
  docs/types.rst
  google/__init__.py
  google/cloud/__init__.py
  google/cloud/pubsublite/cloudpubsub/__init__.py
  google/cloud/pubsublite/types/__init__.py
  samples/snippets/create_lite_subscription_example.py
  samples/snippets/create_lite_topic_example.py
  samples/snippets/delete_lite_subscription_example.py
  samples/snippets/delete_lite_topic_example.py
  samples/snippets/get_lite_subscription_example.py
  samples/snippets/get_lite_topic_example.py
  samples/snippets/list_lite_subscriptions_in_project_example.py
  samples/snippets/list_lite_subscriptions_in_topic_example.py
  samples/snippets/list_lite_topics_example.py
  samples/snippets/subscriber_example.py
  samples/snippets/update_lite_subscription_example.py
  samples/snippets/update_lite_topic_example.py
Labels: api: pubsublite, cla: yes

#72 samples: install lib from pypi and correct region tag
  samples/snippets/noxfile.py
  samples/snippets/publish_with_batch_settings_example.py
  samples/snippets/requirements.txt
Labels: api: pubsublite, cla: yes, samples
