Repository googleapis/python-pubsublite, pull requests merged in 2021-06, with the labels that each got.

#124 fix: shutdown event loop if publisher fails to start and set exception on result future
  google/cloud/pubsublite/cloudpubsub/internal/multiplexed_publisher_client.py
  google/cloud/pubsublite/internal/wire/partition_count_watching_publisher.py
  log.txt
  tests/unit/pubsublite/cloudpubsub/internal/multiplexed_publisher_client_test.py
  tests/unit/pubsublite/internal/wire/partition_count_watching_publisher_test.py
Labels: api: pubsublite, cla: yes

#154 refactor: Pass last stream error to ConnectionReinitializer.reinitialize
  google/cloud/pubsublite/internal/wire/assigner_impl.py
  google/cloud/pubsublite/internal/wire/committer_impl.py
  google/cloud/pubsublite/internal/wire/connection_reinitializer.py
  google/cloud/pubsublite/internal/wire/retrying_connection.py
  google/cloud/pubsublite/internal/wire/single_partition_publisher.py
  google/cloud/pubsublite/internal/wire/subscriber_impl.py
  tests/unit/pubsublite/internal/wire/retrying_connection_test.py
Labels: api: pubsublite, cla: yes

#157 chore: update codeowners
  .github/CODEOWNERS
Labels: api: pubsublite, automerge, cla: yes

#159 fix: Add admin interfaces for reservations
  google/cloud/pubsublite/admin_client.py
  google/cloud/pubsublite/admin_client_interface.py
  google/cloud/pubsublite/cloudpubsub/internal/ack_set_tracker.py
  google/cloud/pubsublite/cloudpubsub/internal/make_publisher.py
  google/cloud/pubsublite/cloudpubsub/internal/make_subscriber.py
  google/cloud/pubsublite/cloudpubsub/internal/single_publisher.py
  google/cloud/pubsublite/cloudpubsub/internal/single_subscriber.py
  google/cloud/pubsublite/cloudpubsub/message_transformer.py
  google/cloud/pubsublite/cloudpubsub/nack_handler.py
  google/cloud/pubsublite/cloudpubsub/publisher_client_interface.py
  google/cloud/pubsublite/cloudpubsub/subscriber_client_interface.py
  google/cloud/pubsublite/internal/wire/admin_client_impl.py
  google/cloud/pubsublite/internal/wire/assigner.py
  google/cloud/pubsublite/internal/wire/committer.py
  google/cloud/pubsublite/internal/wire/default_routing_policy.py
  google/cloud/pubsublite/internal/wire/make_publisher.py
  google/cloud/pubsublite/internal/wire/merge_metadata.py
  google/cloud/pubsublite/internal/wire/permanent_failable.py
  google/cloud/pubsublite/internal/wire/publisher.py
  google/cloud/pubsublite/internal/wire/retrying_connection.py
  google/cloud/pubsublite/internal/wire/routing_policy.py
  google/cloud/pubsublite/internal/wire/serial_batcher.py
  google/cloud/pubsublite/internal/wire/subscriber.py
  google/cloud/pubsublite/testing/test_utils.py
  google/cloud/pubsublite/types/location.py
  google/cloud/pubsublite/types/paths.py
Labels: api: pubsublite, cla: yes

#170 chore: add yoshi-python team to code owners
  .github/CODEOWNERS
Labels: api: pubsublite, cla: yes

#162 fix(deps): add packaging requirement
  setup.py
  testing/constraints-3.6.txt
Labels: api: pubsublite, cla: yes, kokoro:force-run

#161 fix: exclude docs and tests from package
  setup.py
Labels: api: pubsublite, cla: yes
